### ISSUE TITLE
Cant specify a directory

### ISSUE THREAD

**Issue by adambiggs** [Numkil/ag.nvim#4]
Running `:Ag search-term directory` using this fork fails with the message `No matches for "search-term directory"`.

But the same command works fine with the upstream `rking/ag.vim` version.

**Comment by Numkil** [comment]
I'll will look into it tonight or tomorrow morning, it doesn't work atm you are right.
But as soon as it works if you use the option to search from the root of the project you will always have to write either the full path or the path relative to the project root.

**Comment by adambiggs** [comment]
Thanks for the quick response!

Currently I use the `ag` CLI in a Tmux pane from the project root, so using a path relative to the project root makes perfect sense.

**Comment by Numkil** [comment]
I actually already realized the problem I'm putting everything in a single set of escape parentheses, I'll fix it as soon as I finished work.

**Comment by Numkil** [comment]
Could you test this for me when you got the time? It works for me personally. I really need to start writing some tests for ag.nvim :p

**Comment by adambiggs** [comment]
It works! thanks :beers:

**Comment by Numkil** [comment]
Great, thanks for making an issue
