### ISSUE TITLE
Feature request: mapping to search for selection or entity

### ISSUE THREAD

**Issue by cprn** [Numkil/ag.nvim#9]
By entity I mean the word under cursor. And by selection I mean with auto-escaping. It should probably utilize `--php`, `--cpp` and similar flags as well.

**Comment by Numkil** [comment]
@cprn Hi. I think what you are asking about already works with the plugin. Executing the :Ag or :LAg commands without specifying a parameter will trigger it to search for the word under your cursor. 

Also I don't see why you would limit the search results to a specific file type. I often want to search through different types at the same time. (php, js, twig) for example. If you can provide me for a good usecase of that feature, I might be willing to implement an option you can enable/disable that limits ag to searching for the filetype of the file you are currently looking at.

**Comment by cprn** [comment]
> Executing the :Ag or :LAg commands without specifying a parameter will trigger it to search for the word under your cursor.

Ahh! Thanks a lot, makes much more sense now! 👍 

> Also I don't see why you would limit the search results to a specific file type.

You're right. I was convinced `ag` does something smarter with those flags than just filtering file types. My bad, sorry. I'll just make it ignore `ctags` files somehow and it should resolve all my issues.
